spring:
  application:
    name: SmartSupportDesk

  ai:
    bedrock:
      region: ${AWS_REGION:eu-west-1}
      converse:
        chat:
          options:
            model: ${BEDROCK_MODEL_ID:amazon.nova-lite-v1:0}
    embedding:
      transformer:
        onnx:
          model-uri: https://huggingface.co/intfloat/e5-small-v2/resolve/main/model.onnx
        tokenizer:
          uri: https://huggingface.co/intfloat/e5-small-v2/raw/main/tokenizer.json


log:
  level:
    org.springframework.ai: DEBUG
    org.springframework.boot.autoconfigure: DEBUG


